language: php

php:
  - 5.5
  - 5.6
  - 7

env:
  matrix:
  - TYPO3_VERSION="^6.2.0"
  - TYPO3_VERSION="^7.6.0"
  - TYPO3_VERSION="^8.5"

matrix:
  exclude:
    - php: 5.5
      env: TYPO3_VERSION="^8.5"
    - php: 5.6
      env: TYPO3_VERSION="^8.5"
    - php: 7
      env: TYPO3_VERSION="^6.2.0"

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update

before_script:
  - composer require typo3/cms="$TYPO3_VERSION"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.build/

script:
  - >
    echo;
    echo "Running unit tests";
    .build/bin/phpunit -c .build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/

  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .build/bin/phpunit --colors  -c .build/vendor/typo3/cms/typo3/sysext/core/Build/FunctionalTests.xml {}'
